version: '3'
services:
  # Basic postgres database
  database:
    image: "postgres"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    volumes:
      - database-data:/var/lib/postgresql/data/

  # initialisation job for the database
  # it:
  #   - waits for the db to be online
  #   - runs the migration scripts
  #   - populates the database with random data
  #       - (checking first that there is no data, so re-starts are safe)
  dbinit:
    build:
      dockerfile: build/Dockerfile.dbinit
      context: ..
    environment:
      - PGHOST=database
      - PGPORT
      - PGUSER
      - PGPASSWORD
      - PGDATABASE
      - SERVE_IP
      - SERVE_PORT
      - SERVE_WRITE_TIMEOUT
      - SERVE_READ_TIMEOUT

volumes:
  database-data:
